### ISSUE TITLE
conda create issues 

### ISSUE THREAD

**Issue by bhill-17** [nanoporetech/pipeline-umi-amplicon#2]
Hello I am having trouble with the line of code 
conda env create -f environment.yml Errors populate in Std output indicating that pip failed 

![image](https://user-images.githubusercontent.com/51204078/96911888-79a95d00-146f-11eb-8f33-793fb819cc67.png)
![image](https://user-images.githubusercontent.com/51204078/96911922-89c13c80-146f-11eb-905d-2f46fe673c7c.png)

**Comment by cjw85** [comment]
Hi @bhill-17,

The issues here stem from an inability to compile some dependencies of the medaka program. I have changed how medaka is installed into the conda environment which should allow the `conda env create` command to proceed more smoothly.

Please try updating your copy of the code (`git pull origin master`) and attempt to create the environment again.

**Comment by bhill-17** [comment]
I updated the copy of of the code that I have but it's still having issues. Below are the issues I'm seeing 
![image](https://user-images.githubusercontent.com/51204078/97010877-fd1c8a00-1513-11eb-9d68-4a8ec0cfed5e.png)
![image](https://user-images.githubusercontent.com/51204078/97010928-0d346980-1514-11eb-8978-822a9cab17d9.png)

**Comment by cjw85** [comment]
@bhill-17,

I'm investigating ways through this dependency conflict.

**Comment by cjw85** [comment]
Closed with https://github.com/nanoporetech/pipeline-umi-amplicon/issues/3
