### ISSUE TITLE
test if installation was successful 

### ISSUE THREAD

**Issue by bhill-17** [nanoporetech/pipeline-umi-amplicon#3]
Hi I've progressed past the conda issue and am now not sure what is wrong with the installation testing command. I am not trying to use my own data yet. I'm just trying to get the setup right. Below is the code I used and the output. So can you help me figure out why this step isn't working? 

<img width="1053" alt="Screen Shot 2020-10-26 at 9 01 38 AM" src="https://user-images.githubusercontent.com/51204078/97176187-f6d41b00-176a-11eb-84b0-77080500ee5f.png">

**Comment by cjw85** [comment]
@bhill-17 We've just made a few small changes to both the creation of the conda environment and the snakemake pipeline itself. Installation and the example should now run smoothly. Please open another issue if it does not.
